// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import './src/config/env.config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
});
